"use client";

import { useEffect, useMemo, useState } from "react";
import { Maximize2, Minimize2, Plus, Search, RotateCcw, Users, UserRoundCheck, ShieldAlert, GraduationCap, ArrowUpRight, X } from "lucide-react";

type Row = Record<string, any>;
const colors = { base: "#0b0d12", surface: "#11151d", surface2: "#171c25", border: "#26303d", accent: "#38bdf8", accent2: "#22d3ee", text: "#e6edf5", muted: "#8491a1", success: "#34d399", warning: "#fbbf24", danger: "#fb7185" };
const dimensions = [
  ["الجنس", "Gender"], ["المجال_العمري", "Age group"], ["famille_professionnelle", "Professional family"],
  ["الرتبة_الحالية", "Current grade"], ["المجال_الخبرة_المهنية", "Professional seniority"], ["المجال_في_الرتبة_الحالية", "Grade seniority"],
  ["المجال_في_الدرجات", "Echelon seniority"], ["الحركة", "Movement"],
] as const;
const get = (r: Row, k: string) => r[k] == null || r[k] === "" ? "—" : String(r[k]);
function Chart({ title, question, values, kind = "bar", dense = false }: { title: string; question: string; values: [string, number][]; kind?: "bar" | "donut"; dense?: boolean }) {
  const total = values.reduce((a, [,v]) => a + v, 0) || 1;
  const max = Math.max(...values.map(([,v]) => v), 1);
  return <section className={`rounded-2xl border p-5 ${dense ? "min-h-[430px]" : "min-h-[280px]"}`} style={{background: colors.surface, borderColor: colors.border, boxShadow: `0 0 28px rgba(56,189,248,.045)`}}>
    <div className="mb-4"><div className="text-sm font-semibold" style={{color:colors.text}}>{title}</div><div className="text-xs mt-1" style={{color:colors.muted}}>{question}</div></div>
    {kind === "donut" ? <div className="flex gap-5 items-center"><div className="relative h-40 w-40 shrink-0 rounded-full" style={{background:`conic-gradient(${colors.accent} 0 ${Math.min(100, values[0]?.[1] / total * 100 || 0)}%, ${colors.accent2} 0 100%)`, boxShadow:`0 0 22px rgba(56,189,248,.18)`}}><div className="absolute inset-7 rounded-full flex items-center justify-center text-xl font-bold" style={{background:colors.surface,color:colors.text}}>{total}</div></div><div className="space-y-2">{values.map(([k,v],i)=><div key={k} className="flex gap-3 text-xs"><span className="h-2 w-2 rounded-full mt-1" style={{background:i?colors.accent2:colors.accent}}/><span style={{color:colors.muted}}>{k}</span><b style={{color:colors.text}}>{v}</b></div>)}</div></div> : <div className="space-y-3 overflow-auto pr-1 max-h-[340px]">{values.map(([k,v])=><div key={k} className="grid grid-cols-[minmax(120px,1fr)_2fr_40px] gap-3 items-center text-xs"><span className="truncate" title={k} style={{color:colors.muted}}>{k}</span><div className="h-2 rounded-full" style={{background:colors.surface2}}><div className="h-full rounded-full" style={{width:`${v/max*100}%`,background:colors.accent,boxShadow:`0 0 12px rgba(56,189,248,.35)`}}/></div><b style={{color:colors.text,textAlign:"right"}}>{v}</b></div>)}</div>}
  </section>
}

export default function HRDashboard() {
  const [rows,setRows]=useState<Row[]>([]); const [tab,setTab]=useState("Dashboard"); const [active,setActive]=useState<Record<string,string[]>>({}); const [query,setQuery]=useState(""); const [fs,setFs]=useState(false); const [modal,setModal]=useState(false); const [form,setForm]=useState<Row>({}); const [error,setError]=useState(""); const [loading,setLoading]=useState(true);
  useEffect(()=>{fetch("/api/hr").then(r=>r.ok?r.json():Promise.reject()).then(x=>setRows(x.records||[])).catch(()=>setRows([])).finally(()=>setLoading(false))},[]);
  useEffect(()=>{const on=()=>setFs(Boolean(document.fullscreenElement)); document.addEventListener("fullscreenchange",on); return()=>document.removeEventListener("fullscreenchange",on)},[]);
  const filtered=useMemo(()=>rows.filter(r=>dimensions.every(([k])=>!active[k]?.length||active[k].includes(get(r,k)))&&Object.values(r).some(v=>String(v??"").toLowerCase().includes(query.toLowerCase()))),[rows,active,query]);
  const counts=(k:string)=>Object.entries(filtered.reduce((a:any,r)=>{const v=get(r,k);a[v]=(a[v]||0)+1;return a},{})).sort((a,b)=>(b[1] as number)-(a[1] as number)) as [string,number][];
  const avg=(k:string)=>{const v=filtered.map(r=>Number(r[k])).filter(Number.isFinite);return v.length?(v.reduce((a,b)=>a+b,0)/v.length):0};
  const age55=filtered.filter(r=>Number(r.age??r["العمر"])>=55).length, age60=filtered.filter(r=>Number(r.age??r["العمر"])>=60).length;
  const alertRows=filtered.filter(r=>Number(r["العمر"])>=60||Number(r["الخبرة_في_الدرجة"])>=3.5||get(r,"ملاحظة")!=="—");
  const years=counts("تاريخ_الدخول").length ? (()=>{const m:any={}; filtered.forEach(r=>{const d=get(r,"تاريخ_الدخول");if(d!=="—"){const y=d.slice(0,4);m[y]=(m[y]||0)+1}});return Object.entries(m).sort() as [string,number][]})():[];
  const toggle=(k:string,v:string)=>setActive(a=>({...a,[k]:a[k]?.includes(v)?a[k].filter(x=>x!==v):[...(a[k]||[]),v]}));
  const clear=()=>setActive({});
  async function fullscreen(){if(!document.fullscreenElement) await document.documentElement.requestFullscreen(); else await document.exitFullscreen()}
  async function add(){setError(""); const d={...form,"N°":Number(form["N°"])}; const res=await fetch("/api/hr",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(d)}); const x=await res.json(); if(!res.ok){setError(x.error||"Invalid record");return} setRows(rs=>[...rs.filter(r=>get(r,"N°")!==get(d,"N°")),d].sort((a,b)=>Number(a["N°"])-Number(b["N°"])));setModal(false);setForm({});}
  return <div id="hr-root" className="min-h-screen" style={{background:colors.base,color:colors.text}}>
    <header className="sticky top-0 z-30 border-b backdrop-blur-xl" style={{background:"rgba(11,13,18,.92)",borderColor:colors.border}}><div className="max-w-[1600px] mx-auto px-5 py-3 flex items-center gap-5"><div className="min-w-0"><div className="text-sm font-bold tracking-wide">HR ANALYTICS <span style={{color:colors.accent}}>/</span> DIRECTION GÉNÉRALE DES DOMAINES</div><div className="text-[10px] mt-1" style={{color:colors.muted}}>Workforce intelligence · data as of 02 Sep 2026</div></div><nav className="ml-auto flex rounded-xl p-1" style={{background:colors.surface2}}>{["Dashboard","Records"].map(x=><button key={x} onClick={()=>setTab(x)} className="px-4 py-2 rounded-lg text-xs" style={{background:tab===x?colors.accent:"transparent",color:tab===x?colors.base:colors.muted}}>{x}</button>)}</nav><button onClick={fullscreen} className="p-2 rounded-lg border" style={{borderColor:colors.border}} title="Fullscreen">{fs?<Minimize2 size={16}/>:<Maximize2 size={16}/>}</button></div></header>
    <div className="max-w-[1600px] mx-auto grid grid-cols-[290px_minmax(0,1fr)] gap-5 p-5">
      <aside className="self-start sticky top-[78px] max-h-[calc(100vh-98px)] overflow-y-auto rounded-2xl border p-4" style={{background:colors.surface,borderColor:colors.border}}><div className="flex justify-between items-center mb-3"><div className="text-xs font-bold">FILTERS</div><button onClick={clear} className="text-[10px]" style={{color:colors.accent}}>Reset</button></div><div className="relative mb-4"><Search size={14} className="absolute left-3 top-2.5" style={{color:colors.muted}}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search records…" className="w-full rounded-lg border py-2 pl-9 pr-2 text-xs outline-none" style={{background:colors.surface2,borderColor:colors.border,color:colors.text}}/></div>{dimensions.map(([k,label])=>{const vals=counts(k); return <div key={k} className="mb-5"><div className="text-[11px] font-semibold mb-2" style={{color:colors.muted}}>{label}</div>{vals.slice(0,12).map(([v,n])=><label key={v} className="flex gap-2 items-center py-1 text-[11px] cursor-pointer"><input type="checkbox" checked={!!active[k]?.includes(v)} onChange={()=>toggle(k,v)} className="accent-cyan-400"/><span className="truncate" title={v} style={{color:colors.text}}>{v}</span><span className="ml-auto" style={{color:colors.muted}}>{n}</span></label>)}</div>})}</aside>
      <main className="min-w-0 space-y-5">{tab==="Dashboard"?<><section className="grid grid-cols-2 lg:grid-cols-5 gap-3">{[["WORKFORCE",filtered.length,Users],["AVG AGE",avg("العمر").toFixed(1),UserRoundCheck],["AGE ≥55",age55,ShieldAlert],["AGE ≥60",age60,ShieldAlert],["HIGH POSITIONS",filtered.filter(r=>get(r,"المنصب_العالي")!=="—"||get(r,"الوظيفة_العليا")!=="—").length,GraduationCap]].map(([t,v,I]:any)=><div key={t} className="rounded-2xl border p-4" style={{background:colors.surface,borderColor:colors.border}}><div className="flex justify-between"><span className="text-[10px] tracking-widest" style={{color:colors.muted}}>{t}</span><I size={16} style={{color:colors.accent}}/></div><div className="text-2xl font-bold mt-3">{loading?"—":v}</div><div className="text-[9px] mt-1" style={{color:colors.muted}}>vs prior period: unavailable in source</div></div>)}</section>
        <div className="grid grid-cols-1 xl:grid-cols-2 gap-5"><Chart title="Age structure" question="How is the workforce distributed by age?" values={counts("المجال_العمري")} /><Chart title="Professional families" question="Which professional families carry the workforce?" values={counts("famille_professionnelle")} /></div>
        <Chart title="Current-grade distribution" question="Which current grades have the largest headcount?" values={counts("الرتبة_الحالية")} dense />
        <div className="grid grid-cols-1 xl:grid-cols-2 gap-5"><Chart title="Professional seniority" question="How experienced is the workforce?" values={counts("المجال_الخبرة_المهنية")} /><Chart title="Seniority in current grade" question="Where is grade tenure concentrated?" values={counts("المجال_في_الرتبة_الحالية")} /></div>
        <div className="grid grid-cols-1 xl:grid-cols-2 gap-5"><Chart title="Echelon seniority" question="How many employees are at each reference tenure band?" values={counts("المجال_في_الدرجات")} /><Chart title="Workforce by gender" question="What is the gender composition?" values={counts("الجنس")} kind="donut" /></div>
        <div className="grid grid-cols-1 xl:grid-cols-2 gap-5"><Chart title="Entries by year" question="When did employees enter the institution?" values={years} dense /><Chart title="Movements" question="What movement statuses are recorded?" values={counts("الحركة")} /></div>
        <section className="rounded-2xl border p-5" style={{background:colors.surface,borderColor:colors.border}}><div className="flex justify-between mb-3"><div><div className="text-sm font-semibold">HR attention queue</div><div className="text-xs mt-1" style={{color:colors.muted}}>Records surfaced by age, echelon tenure, or source notes.</div></div><span className="text-xl font-bold" style={{color:colors.warning}}>{alertRows.length}</span></div><div className="overflow-auto"><table className="w-full text-xs"><thead><tr className="text-left" style={{color:colors.muted}}><th className="py-2">Employee</th><th>Current grade</th><th>Age</th><th>Echelon tenure</th><th>Note</th></tr></thead><tbody>{alertRows.slice(0,12).map(r=><tr key={r["N°"]} className="border-t" style={{borderColor:colors.border}}><td className="py-2">{get(r,"الإسم")} {get(r,"اللقب")}</td><td>{get(r,"الرتبة_الحالية")}</td><td>{get(r,"العمر")}</td><td>{get(r,"الخبرة_في_الدرجة")} y</td><td className="max-w-[280px] truncate">{get(r,"ملاحظة")}</td></tr>)}</tbody></table></div></section>
      </>:<Records rows={filtered} onAdd={()=>setModal(true)}/>}</main></div>
    {modal&&<div className="fixed inset-0 z-50 grid place-items-center p-5" style={{background:"rgba(0,0,0,.72)"}}><div className="w-full max-w-2xl rounded-2xl border p-5 max-h-[90vh] overflow-auto" style={{background:colors.surface,borderColor:colors.border}}><div className="flex justify-between"><b>Add record</b><button onClick={()=>setModal(false)}><X size={18}/></button></div><div className="grid grid-cols-2 gap-3 mt-4">{[["N°","ID"],["Nom","Last name"],["Prénom","First name"],["الرتبة_الحالية","Current grade"],["تاريخ_الإزدياد","Birth date"],["تاريخ_الدخول","Entry date"],["تعيين_في_الرتبة_الحالية","Current grade appointment"],["الدرجة","Echelon"]].map(([k,l])=><label key={k} className="text-[10px]" style={{color:colors.muted}}>{l}<input type={k.includes("تاريخ")?"date":"text"} value={form[k]??""} onChange={e=>setForm({...form,[k]:e.target.value})} className="mt-1 w-full rounded-lg border p-2 text-xs outline-none" style={{background:colors.surface2,borderColor:colors.border,color:colors.text}}/></label>)}</div>{error&&<div className="text-xs mt-3" style={{color:colors.danger}}>{error}</div>}<button onClick={add} className="mt-4 px-4 py-2 rounded-lg text-xs font-semibold" style={{background:colors.accent,color:colors.base}}>Save record</button></div></div>}
  </div>
}
function Records({rows,onAdd}:{rows:Row[],onAdd:()=>void}){const [sort,setSort]=useState("N°");const [desc,setDesc]=useState(false);const sorted=[...rows].sort((a,b)=>{const x=String(a[sort]??""),y=String(b[sort]??"");return (x.localeCompare(y,"ar",{numeric:true})||0)*(desc?-1:1)});const cols=["N°","اللقب","الإسم","الجنس","الرتبة_الحالية","العمر","تاريخ_الدخول","الدرجة","الخبرة_في_الرتبة","الحركة"];return <section className="rounded-2xl border overflow-hidden" style={{background:colors.surface,borderColor:colors.border}}><div className="p-4 flex items-center justify-between"><div><div className="text-sm font-semibold">Records</div><div className="text-xs mt-1" style={{color:colors.muted}}>{rows.length} filtered records</div></div><button onClick={onAdd} className="flex items-center gap-2 px-3 py-2 rounded-lg text-xs font-semibold" style={{background:colors.accent,color:colors.base}}><Plus size={14}/> Add record</button></div><div className="overflow-auto max-h-[75vh]"><table className="w-full text-xs"><thead className="sticky top-0" style={{background:colors.surface2}}><tr>{cols.map(c=><th key={c} className="p-3 text-left whitespace-nowrap cursor-pointer" style={{color:colors.muted}} onClick={()=>{if(sort===c)setDesc(!desc);else{setSort(c);setDesc(false)}}}>{c}</th>)}</tr></thead><tbody>{sorted.map(r=><tr key={r["N°"]} className="border-t hover:bg-white/[.025]" style={{borderColor:colors.border}}>{cols.map(c=><td key={c} className="p-3 whitespace-nowrap max-w-[280px] truncate" title={get(r,c)}>{get(r,c)}</td>)}</tr>)}</tbody></table></div></section>}
